name: pizzahut
description: Pizza Hut Flutter project for UEE.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #http: ^0.13.3
  #provider: ^6.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.5.3
  provider: ^6.0.0
  http: ^0.13.3
  #http: ^0.12.0+4
  flutter_svg: ^0.19.1
  page_transition: ^2.0.4
  flutter_signin_button: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home/PizzaHutLogoHome.png
    - assets/images/home/Image1.jpg
    - assets/images/home/Image2.jpg
    - assets/images/home/Image3.jpg
    - assets/images/home/Image7.jpg
    - assets/images/appetizers/appetizerImage1.jpg
    - assets/images/appetizers/appetizerImage2.jpg
    - assets/images/appetizers/appetizerImage3.jpg
    - assets/images/appetizers/appetizerImage4.jpg
    - assets/images/appetizers/appetizerImage5.jpg
    - assets/images/appetizers/appetizerImage6.jpg
    - assets/images/appetizers/appetizerImage7.jpg
    - assets/images/appetizers/appetizerImage8.jpg
    - assets/images/appetizers/appetizerImage9.jpg
    - assets/images/appetizers/appetizerImage10.jpg
    - assets/images/beverages/Image1.jpg
    - assets/images/beverages/Image2.jpg
    - assets/images/beverages/Image3.jpg
    - assets/images/beverages/Image4.jpg
    - assets/images/beverages/Image5.jpg
    - assets/images/beverages/Image6.jpg
    - assets/images/beverages/Image7.jpg
    - assets/images/beverages/Image8.jpg
    - assets/images/beverages/Image9.jpg
    - assets/images/beverages/Image10.jpg
    - assets/images/beverages/Image11.jpg
    - assets/images/beverages/Image12.jpg
    - assets/images/desserts/Image1.jpg
    - assets/images/desserts/Image2.jpg
    - assets/images/desserts/Image3.jpg
    - assets/images/pastas/Image1.jpg
    - assets/images/pastas/Image2.jpg
    - assets/images/pastas/Image3.jpg
    - assets/images/pastas/Image4.jpg
    - assets/images/promos/Image1.jpg
    - assets/images/promos/Image2.jpg
    - assets/images/promos/Image3.jpg
    - assets/images/promos/Image4.jpg
    - assets/images/promos/Image5.jpg
    - assets/images/promos/Image6.jpg
    - assets/images/promos/Image7.jpg
    - assets/images/promos/Image8.jpg
    - assets/images/atc/atc_background.png
    - images/pizza_hut_logo.png
    - images/pizza_hut_logo2.png
    - images/pizza_main.jpg
    - images/pasta_main.jpg
    - images/cheesy_garlic_bread_main.jpg
    - images/lava_cake_main.jpg
    - images/chocolate_milkshake_main.jpg
    - images/promo_main.jpg
    - images/pizza/bbq_chicken_pizza.jpg
    - images/pizza/black_chicken_pizza.jpg
    - images/pizza/cheese_lovers_pizza.jpg
    - images/pizza/hotspicy_chicken.jpg
    - images/vege_pizza.jpg
    - assets/images/gets_started_page/
    - assets/images/splash_page/
    - assets/images/login_page/
    - assets/images/register_page/
    - assets/images/view_profile_page/
    - assets/images/promo_pizza/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
